[versions]
agp = "8.8.0"
androidx-activity = "1.9.3"
kotlin = "2.1.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
android-material = "com.google.android.material:material:1.12.0"
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
