[versions]
junit4 = "4.12"
kotlin = "2.1.0"
slf4j = "1.7.36"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
junit4 = { module = "junit:junit", version.ref = "junit4" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
